### ISSUE TITLE
Support .NET Standard

### ISSUE THREAD

**Issue by gsomix** [fsprojects/FSharp.Core.Fluent#10]
What do you think about targeting this library to `netstandard1.6` and moving project file to new .NET SDK?

**Comment by dsyme** [comment]
@gsomix Absolutely, please go ahead, if you'd like to contribute this it would be great

**Comment by gsomix** [comment]
OK, thanks! It will be a good exercise.

**Comment by ForNeVeR** [comment]
@dsyme, @forki, gentlemen, I'm sorry to bother you, but — any news on this? It seems like PR #11 is ready for merge!

**Comment by forki** [comment]
I'm not a maintainer here. sorry
