### ISSUE TITLE
Project needs a new logo

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Core.Fluent#6]
This project is using the unadorned FSSF Logo for F#.  It needs a new logo - suggestions welcome!

**Comment by dsyme** [comment]
Cc @sergey-tihon - any suggestions?

**Comment by sergey-tihon** [comment]
We already have one in this repo 

![image](https://user-images.githubusercontent.com/1197905/192615625-431dcaca-da41-4214-b2ad-371f61fe3dc0.png)

**Comment by sergey-tihon** [comment]
I can propose two more options that are on top of my mind 

![logo-template 1](https://user-images.githubusercontent.com/1197905/192618583-bca69167-c1d3-476d-815e-f6e9f9171366.png)

![logo-template 2](https://user-images.githubusercontent.com/1197905/192618598-27c2e46d-5b9a-4238-9377-9ff58a8e00b4.png)

**Comment by dsyme** [comment]
Oh that's GREAT I didn't realise :)
