### ISSUE TITLE
F# 4.0 Constructor as first class function does not work for structs

### ISSUE THREAD

**Issue by rookboom** [fsprojects/FSharp.Core.Fluent#8]
The following code does not compile:

``` fsharp
module Test =
    [<Struct>]
    type SparseEntry(index:int, value:float32) =
        member m.Index = index
        member m.Value = value

    let create(items:(int*float32)[]) =
        items.map(SparseEntry)
```

If I remove the `[<Struct>]` attribute it works fine.
Note that if I use standard F# syntax intead of Fluent, it does work.

``` fsharp
items |> Array.map SparseEntry
```

works fine.

**Comment by dsyme** [comment]
This is not strictly a bug, though the error message certainly is not great.  It's just an artefact of overload resolution in the presence of multiple possible extension methods

Here's a version of the example that doesn't copies out the relevant parts of FSharp.Core.Fluent so there's no direct reference to the package:

```

type System.Collections.Generic.IEnumerable<'T> with 
        member inline source.map (mapping:('T -> 'U)) = Seq.map mapping source

type ``[]``<'T> with 
       member inline arr.map mapping = Array.map mapping arr

module Test =
    [<Struct>]
    type SparseEntry(index:int, value:float32) =
        member m.Index = index
        member m.Value = value

    let create(items:(int*float32)[]) =
        items.map(SparseEntry)

```

The difference between structs and classes is that in F# structs always have a default constructor (for better or worse...). The workaround is to eta-expand:

```
let create(items:(int*float32)[]) =
    items.map(fun (a,b) -> SparseEntry (a,b))
```

cheers
don

**Comment by dsyme** [comment]
By design
