### ISSUE TITLE
FSharp.Core.Fluent-4.0 could target framework 4.0

### ISSUE THREAD

**Issue by smoothdeveloper** [fsprojects/FSharp.Core.Fluent#9]
I can't use FSharp.Core.Fluent-4.0 nuget package in my .net 4.0 projects while I can use FSharp.Core 4.4 in them.

It would make sense to change https://github.com/fsprojects/FSharp.Core.Fluent/blob/master/src/FSharp.Core.Fluent-4.0/FSharp.Core.Fluent-4.0.fsproj#L14 to target Framework 4.0 instead.

**Comment by kkm000** [comment]
I like the general approach of targeting the lowest 4.x framework version possible in the most general libraries like this one (and am still getting by with the NuGet-packaged version 4.0.0.1 of FSharp.Core for many of our internal packaged libraries), but [this project depends on the FSharp.Core package version 4.2](https://github.com/fsprojects/FSharp.Core.Fluent/blob/73b09036f/src/FSharp.Core.Fluent/FSharp.Core.Fluent-4.0.fsproj#L28), which [requires net45](https://www.nuget.org/packages/FSharp.Core/4.2.1). The [latest FSharp.Core nuget to declaratively support net40 is 4.1.18](https://www.nuget.org/packages/FSharp.Core/4.1.18) as of this day.

I am a little bit confused (as is probably everyone else) about versions of the assembly itself in these packages, but IIRC (and I probably do not) NuGet packages 4.0.* and 4.1.* package the assembly 4.4.0 (that you use), and the 4.2.* packages contain FSharp.Core 4.4.1.

I am not sure if older FSharp.Cores have all of the target operations in the respective modules. Does it in fact do? If they do, then your suggested change is not only correct but also easy to implement. If it does not, it would still be possible to use something like `#if NET_GE_400/#endif` brackets in the code to limit the set of fluent extentions to their non-fluent counterparts available in the latest net40-packaged Core to produce a net40 build.  ).

@dsyme, @gsomix, what's your take on the importance of targeting net40? On a personal note, coming from the C land of old, I do not find clauses akin to  `#if defined (HAVE_MMAP) && !defined(__fooix)  /* mmap is braindead on Fooix */` *extremely* distasteful, but YMMV. :)

**Comment by dsyme** [comment]
@kkm000 .NET 4.0 seems a very rare target these days, so I cant' imagine we'd adjsut things for that target here

**Comment by dsyme** [comment]
Closing as now netstandard 2.0
